---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - '--allow-multiple-documents'
      - id: check-json
      - id: check-added-large-files
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.8.0
    hooks:
      - id: hadolint
        args:
          - '--ignore'
          - 'DL3007'
          - '--ignore'
          - 'DL3008'
          - '--ignore'
          - 'DL3013'
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - '--max-line-length'
          - '99'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        args:
          # all subprocess calls are checked for exploitability
          - '--skip'
          - 'B404,B603'
  - repo: https://github.com/PyCQA/prospector
    rev: 1.6.0
    hooks:
      - id: prospector

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
