---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - '--allow-multiple-documents'
      - id: check-json
      - id: check-added-large-files
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args:
          - '--ignore'
          - 'DL3007'
          - '--ignore'
          - 'DL3008'
          - '--ignore'
          - 'DL3013'
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - '--max-line-length'
          - '99'
  - repo: https://github.com/PyCQA/prospector
    rev: v1.10.3
    hooks:
      - id: prospector
        args:
          - '--profile'
          - '.ci_config/prospector.yaml'
        additional_dependencies:
          - bandit
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.4
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
